[package]
name = "qcpro"
version = "0.1.0"
authors = ["疯味十三君 <a664554724@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term="*"
qcpro_core={path = "../qcpro_core"}